apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi         # MySQL pod asking for 5GB
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas-lab.home # Connect to the nas on my lan.  There's a share there.  Synology requires Squash=No mapping.
    path: "/volume1/mysql-directory"
