apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: tools  
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
