apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv 
  namespace: tools
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas-lab.home 
    path: "/volume1/kube-postgres-nfs"
