apiVersion: v1
kind: Service
metadata:
  name: postgres-svc  
  namespace: tools
spec:
  type: LoadBalancer
  selector:
    app: postgres 
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
  externalIPs:
  - 192.168.1.10
